// Generated by Supabase CLI
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      departamentos: {
        Row: {
          id: string
          nome: string
          descricao: string | null
          ativo: boolean
          criado_em: string
          atualizado_em: string
        }
        Insert: {
          id?: string
          nome: string
          descricao?: string | null
          ativo?: boolean
          criado_em?: string
          atualizado_em?: string
        }
        Update: {
          id?: string
          nome?: string
          descricao?: string | null
          ativo?: boolean
          criado_em?: string
          atualizado_em?: string
        }
        Relationships: []
      }
      formularios: {
        Row: {
          id: string
          nome: string
          slug: string
          descricao: string | null
          mensagem_fim: string | null
          logo_url: string | null
          data_inicio: string | null
          data_fim: string | null
          mostrar_capa: boolean
          ativo: boolean
          cor_tema: string
          criado_por: string | null
          criado_em: string
          atualizado_em: string
        }
        Insert: {
          id?: string
          nome: string
          slug: string
          descricao?: string | null
          mensagem_fim?: string | null
          logo_url?: string | null
          data_inicio?: string | null
          data_fim?: string | null
          mostrar_capa?: boolean
          ativo?: boolean
          cor_tema?: string
          criado_por?: string | null
          criado_em?: string
          atualizado_em?: string
        }
        Update: {
          id?: string
          nome?: string
          slug?: string
          descricao?: string | null
          mensagem_fim?: string | null
          logo_url?: string | null
          data_inicio?: string | null
          data_fim?: string | null
          mostrar_capa?: boolean
          ativo?: boolean
          cor_tema?: string
          criado_por?: string | null
          criado_em?: string
          atualizado_em?: string
        }
        Relationships: [
          {
            foreignKeyName: 'formularios_criado_por_fkey'
            columns: ['criado_por']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          }
        ]
      }
      matriz_itens: {
        Row: {
          id: string
          pergunta_id: string
          linha: string
          coluna: string
          ordem: number
          criado_em: string
        }
        Insert: {
          id?: string
          pergunta_id: string
          linha: string
          coluna: string
          ordem: number
          criado_em?: string
        }
        Update: {
          id?: string
          pergunta_id?: string
          linha?: string
          coluna?: string
          ordem?: number
          criado_em?: string
        }
        Relationships: [
          {
            foreignKeyName: 'matriz_itens_pergunta_id_fkey'
            columns: ['pergunta_id']
            isOneToOne: false
            referencedRelation: 'perguntas'
            referencedColumns: ['id']
          }
        ]
      }
      perguntas: {
        Row: {
          id: string
          formulario_id: string
          texto: string
          tipo: Database['public']['Enums']['pergunta_tipo']
          obrigatorio: boolean
          ordem: number
          opcoes: Json | null
          validacoes: Json | null
          criado_em: string
          atualizado_em: string
        }
        Insert: {
          id?: string
          formulario_id: string
          texto: string
          tipo: Database['public']['Enums']['pergunta_tipo']
          obrigatorio?: boolean
          ordem: number
          opcoes?: Json | null
          validacoes?: Json | null
          criado_em?: string
          atualizado_em?: string
        }
        Update: {
          id?: string
          formulario_id?: string
          texto?: string
          tipo?: Database['public']['Enums']['pergunta_tipo']
          obrigatorio?: boolean
          ordem?: number
          opcoes?: Json | null
          validacoes?: Json | null
          criado_em?: string
          atualizado_em?: string
        }
        Relationships: [
          {
            foreignKeyName: 'perguntas_formulario_id_fkey'
            columns: ['formulario_id']
            isOneToOne: false
            referencedRelation: 'formularios'
            referencedColumns: ['id']
          }
        ]
      }
      resposta_itens: {
        Row: {
          id: string
          resposta_id: string
          pergunta_id: string
          matriz_item_id: string | null
          valor: string | null
          arquivo_url: string | null
          criado_em: string
        }
        Insert: {
          id?: string
          resposta_id: string
          pergunta_id: string
          matriz_item_id?: string | null
          valor?: string | null
          arquivo_url?: string | null
          criado_em?: string
        }
        Update: {
          id?: string
          resposta_id?: string
          pergunta_id?: string
          matriz_item_id?: string | null
          valor?: string | null
          arquivo_url?: string | null
          criado_em?: string
        }
        Relationships: [
          {
            foreignKeyName: 'resposta_itens_matriz_item_id_fkey'
            columns: ['matriz_item_id']
            isOneToOne: false
            referencedRelation: 'matriz_itens'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'resposta_itens_pergunta_id_fkey'
            columns: ['pergunta_id']
            isOneToOne: false
            referencedRelation: 'perguntas'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'resposta_itens_resposta_id_fkey'
            columns: ['resposta_id']
            isOneToOne: false
            referencedRelation: 'respostas'
            referencedColumns: ['id']
          }
        ]
      }
      respostas: {
        Row: {
          id: string
          formulario_id: string
          respondente_nome: string | null
          respondente_email: string | null
          respondente_departamento: string | null
          ip_address: string | null
          user_agent: string | null
          finalizado: boolean
          criado_em: string
          atualizado_em: string
        }
        Insert: {
          id?: string
          formulario_id: string
          respondente_nome?: string | null
          respondente_email?: string | null
          respondente_departamento?: string | null
          ip_address?: string | null
          user_agent?: string | null
          finalizado?: boolean
          criado_em?: string
          atualizado_em?: string
        }
        Update: {
          id?: string
          formulario_id?: string
          respondente_nome?: string | null
          respondente_email?: string | null
          respondente_departamento?: string | null
          ip_address?: string | null
          user_agent?: string | null
          finalizado?: boolean
          criado_em?: string
          atualizado_em?: string
        }
        Relationships: [
          {
            foreignKeyName: 'respostas_formulario_id_fkey'
            columns: ['formulario_id']
            isOneToOne: false
            referencedRelation: 'formularios'
            referencedColumns: ['id']
          }
        ]
      }
      users: {
        Row: {
          id: string
          email: string
          nome: string
          cargo: string | null
          departamento: string | null
          role: Database['public']['Enums']['user_role']
          ativo: boolean
          ultimo_acesso: string | null
          criado_em: string
          atualizado_em: string
        }
        Insert: {
          id?: string
          email: string
          nome: string
          cargo?: string | null
          departamento?: string | null
          role?: Database['public']['Enums']['user_role']
          ativo?: boolean
          ultimo_acesso?: string | null
          criado_em?: string
          atualizado_em?: string
        }
        Update: {
          id?: string
          email?: string
          nome?: string
          cargo?: string | null
          departamento?: string | null
          role?: Database['public']['Enums']['user_role']
          ativo?: boolean
          ultimo_acesso?: string | null
          criado_em?: string
          atualizado_em?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      calc_nps_stats: {
        Args: {
          p_formulario_id: string
        }
        Returns: Json
      }
    }
    Enums: {
      pergunta_tipo: 'texto_curto' | 'texto_longo' | 'email' | 'numero' | 'data' | 'radio' | 'checkbox' | 'dropdown' | 'likert' | 'nps_simples' | 'matriz_nps' | 'secao' | 'arquivo'
      user_role: 'administrador' | 'visualizador'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
